site_name: Loki Docs
site_description: All my cool things, well documented!
site_author: lokeshreddy
site_url: https://mycoolsiterepo.com
repo_name: lokeshreddy007/loki-docs
repo_url: https://github.com/lokeshreddy007/loki-docs
theme:
    name: material
    palette:
        primary: blue
        accent: white
nav:
    - Home: index.md
    - JavaScript: 
      - javascript/index.md
      - Code Snippets: javascript/code-snippets/index.md
      - Codedamm 50 Days Js: javascript/50-Days-of-JavaScript-by-Codedamn/index.md
      - Tips: javascript/tips.md
    - Node:
      - node/index.md
    - Python :
      - python/index.md
      - Code Snippets: python/code-snippets/scraping.md
      - Tips: python/code-snippets/scraping.md
    - Markdown Addons: mkdocs-examples/addons.md
plugins:
  - section-index
  - search
markdown_extensions:
    - pymdownx.superfences
    - pymdownx.progressbar
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.magiclink:
        repo_url_shortener: True
        repo_url_shorthand: True
        social_url_shorthand: True
        # more options on magiclink https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/#options
        provider: 'github'
    - codehilite:
        # https://help.farbox.com/pygments.html
        pygments_style: 'pastie'
        linenums: False
        # set to false to turn off pygments_style
        noclasses: True
    - pymdownx.tasklist
extra_javascript:
    - js/flowchart-loader.js
    - js/details.js
    - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.8.0/flowchart.min.js
extra_css:
    - css/progress_bar.css
    - css/details.css
    - css/tasklist.css
    - css/custom_tasklist.css
